name: Build Fedora

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "master" ]

jobs:
  build:
    name: Fedora ${{ matrix.fedora_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_version: [ '39', '40' ] # 41 can be added when code is updated for FFmpeg 7
    container: fedora:${{ matrix.fedora_version }}

    steps:
    - uses: actions/checkout@v4

    # After Fedora 40 the containers no longer have 'lsblk'
    - name: Ensure lsblk installed
      run : sudo dnf install -y util-linux

    - name: Install RPM Fusion
      run : |
        sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
        sudo dnf update -y

    - name: Install dependencies
      # On Fedora, rather than use install-qt-action, install the Qt packages from Fedora (qtav-devel and ffmpeg-devel require RPM Fusion repositories)
      run: sudo dnf install -y lsb_release gcc-c++ gnutls-devel libv4l-devel qt5-qtbase-devel qt5-qtquickcontrols2-devel qt5-qtmultimedia-devel qtav-devel systemd-devel alsa-lib-devel libusb1-devel turbojpeg-devel ffmpeg-devel libevdev-devel pulseaudio-libs-devel

    - name: Run qmake
      working-directory: ${{github.workspace}}/src
      run: qmake-qt5

    - name: Run make
      working-directory: ${{github.workspace}}/src
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: qtcam-fedora-${{ matrix.fedora_version }}.zip
        if-no-files-found: 'error'
        path: |
          src/Qtcam
